
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 14 12:11:18 IST 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int RET = 2;
  public static final int ELSE = 14;
  public static final int PLUS = 4;
  public static final int RPAREN = 8;
  public static final int THEN = 15;
  public static final int LOOP = 12;
  public static final int IF = 13;
  public static final int LPAREN = 7;
  public static final int ID = 17;
  public static final int LFB = 10;
  public static final int TYPE = 18;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int NUMBER = 16;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int ASSIGN = 3;
  public static final int RFB = 11;
  public static final int BOOLCONST = 19;
}

